export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: "AR", name: "Arabic", flag: "🇸🇦" },
  { code: "BG", name: "Bulgarian", flag: "🇧🇬" },
  { code: "CS", name: "Czech", flag: "🇨🇿" },
  { code: "DA", name: "Danish", flag: "🇩🇰" },
  { code: "DE", name: "German", flag: "🇩🇪" },
  { code: "EL", name: "Greek", flag: "🇬🇷" },
  { code: "EN-GB", name: "English (UK)", flag: "🇬🇧" },
  { code: "EN-US", name: "English (US)", flag: "🇺🇸" },
  { code: "ES", name: "Spanish", flag: "🇪🇸" },
  { code: "ES-419", name: "Spanish (Latin America)", flag: "🌎" },
  { code: "ET", name: "Estonian", flag: "🇪🇪" },
  { code: "FI", name: "Finnish", flag: "🇫🇮" },
  { code: "FR", name: "French", flag: "🇫🇷" },
  { code: "HU", name: "Hungarian", flag: "🇭🇺" },
  { code: "ID", name: "Indonesian", flag: "🇮🇩" },
  { code: "IT", name: "Italian", flag: "🇮🇹" },
  { code: "JA", name: "Japanese", flag: "🇯🇵" },
  { code: "KO", name: "Korean", flag: "🇰🇷" },
  { code: "LT", name: "Lithuanian", flag: "🇱🇹" },
  { code: "LV", name: "Latvian", flag: "🇱🇻" },
  { code: "NB", name: "Norwegian", flag: "🇳🇴" },
  { code: "NL", name: "Dutch", flag: "🇳🇱" },
  { code: "PL", name: "Polish", flag: "🇵🇱" },
  { code: "PT-BR", name: "Portuguese (Brazil)", flag: "🇧🇷" },
  { code: "PT-PT", name: "Portuguese (Portugal)", flag: "🇵🇹" },
  { code: "RO", name: "Romanian", flag: "🇷🇴" },
  { code: "RU", name: "Russian", flag: "🇷🇺" },
  { code: "SK", name: "Slovak", flag: "🇸🇰" },
  { code: "SL", name: "Slovenian", flag: "🇸🇮" },
  { code: "SV", name: "Swedish", flag: "🇸🇪" },
  { code: "TR", name: "Turkish", flag: "🇹🇷" },
  { code: "UK", name: "Ukrainian", flag: "🇺🇦" },
  { code: "ZH-HANS", name: "Chinese (Simplified)", flag: "🇨🇳" },
  { code: "ZH-HANT", name: "Chinese (Traditional)", flag: "🇹🇼" },
];

/** Source languages use shorter codes (EN instead of EN-GB, etc.) */
export const sourceLangs: Language[] = [
  { code: "AR", name: "Arabic", flag: "🇸🇦" },
  { code: "BG", name: "Bulgarian", flag: "🇧🇬" },
  { code: "CS", name: "Czech", flag: "🇨🇿" },
  { code: "DA", name: "Danish", flag: "🇩🇰" },
  { code: "DE", name: "German", flag: "🇩🇪" },
  { code: "EL", name: "Greek", flag: "🇬🇷" },
  { code: "EN", name: "English", flag: "🇬🇧" },
  { code: "ES", name: "Spanish", flag: "🇪🇸" },
  { code: "ET", name: "Estonian", flag: "🇪🇪" },
  { code: "FI", name: "Finnish", flag: "🇫🇮" },
  { code: "FR", name: "French", flag: "🇫🇷" },
  { code: "HU", name: "Hungarian", flag: "🇭🇺" },
  { code: "ID", name: "Indonesian", flag: "🇮🇩" },
  { code: "IT", name: "Italian", flag: "🇮🇹" },
  { code: "JA", name: "Japanese", flag: "🇯🇵" },
  { code: "KO", name: "Korean", flag: "🇰🇷" },
  { code: "LT", name: "Lithuanian", flag: "🇱🇹" },
  { code: "LV", name: "Latvian", flag: "🇱🇻" },
  { code: "NB", name: "Norwegian", flag: "🇳🇴" },
  { code: "NL", name: "Dutch", flag: "🇳🇱" },
  { code: "PL", name: "Polish", flag: "🇵🇱" },
  { code: "PT", name: "Portuguese", flag: "🇵🇹" },
  { code: "RO", name: "Romanian", flag: "🇷🇴" },
  { code: "RU", name: "Russian", flag: "🇷🇺" },
  { code: "SK", name: "Slovak", flag: "🇸🇰" },
  { code: "SL", name: "Slovenian", flag: "🇸🇮" },
  { code: "SV", name: "Swedish", flag: "🇸🇪" },
  { code: "TR", name: "Turkish", flag: "🇹🇷" },
  { code: "UK", name: "Ukrainian", flag: "🇺🇦" },
  { code: "ZH", name: "Chinese", flag: "🇨🇳" },
];
